# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name: "rsshub"
    arch: "amd64"
    system: "linux"
    path: "./bin"
    mod: "none"
    packSrc: "resource,manifest"
    # version: "v1.0.0"
    extra: ""
